#!/bin/sh

set -x

GIT_WORK_TREE="/your/server/your_repo"
export GIT_WORK_TREE

# This is needed for git push based deploy
git reset --hard

cd $GIT_WORK_TREE
git checkout .

cd backend
npm install
npm run build

cd frontend
npm install
npm run build

rsync -avh /your/server/your_repo/dist/ /var/www/html/your_website
