# This file is used for LetsEncrypt to issue SSL certificates automatically using an already running nginx server 
server {
    listen 80;
    server_name your_website.com www.your_website.com;
    root /var/www/html/your_website/;
    index index.html;
}
